apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment02
  labels:
    app: nginx-test02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test02
  template:
    metadata:
      labels:
        app: nginx-test02
    spec:
      containers:
      - name: nginx02
        image: rifkiknw/nginx-test02:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service02
spec:
  selector:
    app: nginx-test02
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 31111
